### ISSUE TITLE
Regression test- RPM

### ISSUE THREAD

**Issue by preethit** [RedHatQE/pulp-automation#20]
@Feed Repo

- Create Repo with feed 
 -Update the repo
 -Sync & Publish the repo
 -Subscribe & package install from the repo
 -Repo export
- Repo delete
-Orphan remove

@Copy Repo

-Create a repo with feed
-sync the repo
-Create a repo with no feed
-copy repo a to repo b
-Publish the repo
-Subscribe & Package install from the repo

@Upload rpm repo

-Create repo with no feed
-Upload rpms
-publish the Repo
-Subscribe & package install from repo

**Comment by pbartiko** [comment]
Automated test cases in https://github.com/RedHatQE/pulp-automation/tree/master/tests/regression_tests

**Comment by copy** [comment]
Cool
